services:
  repomind-redis:
    image: redis:alpine
    container_name: repomind-redis
    ports:
      - "6379:6379"

  repomind-backend:
    # image: ghcr.io/hasaanhameed/repomind-backend:latest
    build:
      context: ./repomind-backend
      dockerfile: Dockerfile
    container_name: repomind-backend
    expose:
      - "8000"
    env_file:
      - ./repomind-backend/.env
    environment:
      - REDIS_URL=redis://repomind-redis:6379
    depends_on:
      - repomind-redis

  repomind-frontend:
    # image: ghcr.io/hasaanhameed/repomind-frontend:latest
    build:
      context: ./repomind-frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    container_name: repomind-frontend
    ports:
      - "80:80"
    depends_on:
      - repomind-backend

volumes:
  redis_data:
